notifications:
  slack:
    - rooms:
        secure: "LrYGnyXrptXwqHv2pMLj5XzklBF92r0rVZolpMR2t1GMFF69KhUcX5KYk76ZeaUPnUhDILRKT7Cc7+9+ptuptpCPAdDC7hxUNn71JWEVPcTB8uLsbtcc8nMGpdzZGOIkj/4GMnfjbljkUeIVnJ0slF2GgWZrRvAYEn4Yp45xTMULKaQTRsozIINTtzofebrwFS4svV2uDBUbebgJEUjTM/dO6OPAptG+DQj85UAskD+HZfaXpMPC4kve6fqUvJVppeEym/UX0JHYdP87txos9rCuD78HI5RxR0BVM07bwzuMBk8G5rLLMrqrvf2O2g5p+sHuVkRwCh0Y3osB0H+RWKVtaZksFlNFnDxwaJ+J8gIg2oCgvOonah1ZPBGnnSV5uMFAgXb5uk+SMqdJfdvqPLQ3ECBxSFFSIQMt63MfG2r2590sZuJkh2mXKDc6skI9pqGA2Rfya8WcRzh3EBwWFbSbhyR4XnWq5beyzSjbfGgeE9zGaElgPkSaiWOw7/A8B5J56/Nrl5tt2DR4hjQLmCQkZx9YGfYGl5o+wM/wGktdq2Ut5fokkIxzzNi5ammk06ZlDOGfqzP+EHicrGU/aFSKty/wKLG4hRt2l8/4K6IH2VnZowiBRkOK2a7Ga1NTTcT8jJfGAL2hwnnbGE802i7ifp3yw0/SZ+En/sybVus="
      on_pull_requests: false
      on_failure: always
      on_success: always
      template:
        - "Build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) of %{repository_slug}@%{branch} by %{author} %{result} in %{duration}"

