notifications:
  slack:
    rooms: alfresco:ZM83bPYfMgqqodY3X9k8hrPC
    on_pull_requests: false
    on_failure: always
    on_success: always
    template:
      - "Repo `%{repository_slug}` *%{result}* build (<%{build_url}|#%{build_number}>) for commit (<%{compare_url}|%{commit}>) on branch `%{branch}`."
      - "Author: %{author} Execution time: *%{duration}*"
      - "Message: %{message}"
